# Site settings
# These are accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tai Chi Practice Videos
email: clarkda@kennedykrieger.org
description: > # this means to ignore newlines until "baseurl:"
  Videos for home practice of the KKI / CNIR Tai Chi curriculum. Please let Dav
  know if you have any problems! This site is maintained entirely by Dav and is
  not specifically endorsed by Kennedy Krieger.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://taichi.reallygoodmoving.com"

# Build settings
markdown: kramdown
theme: minima
