# Site settings
# These are accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Tai Chi Practice Videos
author: Dav Clark
email: clarkda@kennedykrieger.org
description: > # this means to ignore newlines until "baseurl:"
  Videos for home practice of the KKI / CNIR Tai Chi curriculum. Please let Dav
  know if you have any problems! This site is maintained entirely by Dav and is
  not specifically endorsed by Kennedy Krieger.
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

# Works with Dreamhost setup, which deploys from a public dir
destination: ../taichi.reallygoodmoving.com
keep_files: ["videos"]

# Build settings
markdown: kramdown
theme: minima

exclude:
  - Gemfile*
  - '*.elm'
  - Makefile
  - elm-*

google_analytics: UA-85637629-1

# Below are GitHub pages defaults / mods (noted in comments)
github: [metadata]
kramdown:
  input: GFM
  hard_wrap: false
# Don't actually care to have these installed...
# gems:
#   - jekyll-coffeescript
#   - jekyll-paginate
